#!/usr/bin/env bash

go get github.com/cenk/backoff
go get github.com/containous/flaeg
go get github.com/containous/staert
go get github.com/coreos/go-systemd/daemon
go get github.com/sirupsen/logrus

go get golang.org/x/text/secure/bidirule
go get golang.org/x/text/unicode/bidi
go get golang.org/x/text/unicode/norm
go get github.com/coreos/bbolt
go get github.com/hashicorp/consul/api
go get github.com/coreos/etcd/client
go get github.com/coreos/etcd/clientv3
go get github.com/coreos/etcd/clientv3/concurrency
go get github.com/samuel/go-zookeeper/zk
go get github.com/jjcollinge/servicefabric
go get github.com/BurntSushi/ty/fun
go get github.com/eapache/channels
go get github.com/mvdan/xurls
go get github.com/mitchellh/copystructure
go get github.com/elazarl/go-bindata-assetfs
go get github.com/thoas/stats
go get github.com/satori/go.uuid
go get github.com/docker/leadership
go get github.com/mitchellh/hashstructure
go get github.com/go-kit/kit/metrics
go get github.com/vulcand/oxy/roundrobin
go get github.com/go-kit/kit/metrics/dogstatsd
go get github.com/go-kit/kit/log
go get github.com/go-kit/kit/metrics/influx
go get github.com/influxdata/influxdb/client/v2
go get github.com/go-kit/kit/metrics/multi
go get github.com/prometheus/client_golang/prometheus
go get github.com/prometheus/client_golang/prometheus/promhttp
go get github.com/go-kit/kit/metrics/statsd
go get github.com/abbot/go-http-auth
go get github.com/vulcand/oxy/cbreaker
go get github.com/NYTimes/gziphandler
go get github.com/vulcand/oxy/forward
go get github.com/vulcand/oxy/utils
go get github.com/unrolled/secure
go get github.com/urfave/negroni
go get github.com/opentracing/opentracing-go/ext
go get github.com/uber/jaeger-lib/metrics
go get github.com/opentracing/opentracing-go
go get github.com/uber/jaeger-client-go/config
go get github.com/uber/jaeger-client-go/log
go get github.com/openzipkin/zipkin-go-opentracing
go get github.com/xenolf/lego/acme
go get github.com/xenolf/lego/providers/dns
go get github.com/docker/go-connections/nat
go get github.com/docker/docker/api/types
go get github.com/docker/docker/api/types/container
go get github.com/docker/docker/api/types/events
go get github.com/docker/docker/api/types/filters
go get github.com/docker/docker/api/types/swarm
go get github.com/docker/docker/api/types/versions
go get github.com/docker/docker/client
go get github.com/docker/go-connections/sockets
go get github.com/aws/aws-sdk-go/aws/defaults
go get github.com/aws/aws-sdk-go/aws/session
go get github.com/aws/aws-sdk-go/service/dynamodb
go get github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute
go get github.com/aws/aws-sdk-go/service/dynamodb/dynamodbiface
go get github.com/aws/aws-sdk-go/aws
go get github.com/aws/aws-sdk-go/aws/credentials
go get github.com/aws/aws-sdk-go/aws/ec2metadata
go get github.com/aws/aws-sdk-go/aws/request
go get github.com/aws/aws-sdk-go/service/ec2
go get github.com/aws/aws-sdk-go/service/ecs
go get github.com/ArthurHlt/go-eureka-client/eureka
go get gopkg.in/fsnotify.v1
go get k8s.io/api/core/v1
go get k8s.io/api/extensions/v1beta1
go get k8s.io/apimachinery/pkg/apis/meta/v1
go get k8s.io/apimachinery/pkg/fields
go get k8s.io/apimachinery/pkg/labels
go get k8s.io/apimachinery/pkg/runtime
go get k8s.io/apimachinery/pkg/watch
go get k8s.io/client-go/kubernetes
go get k8s.io/client-go/rest
go get k8s.io/client-go/tools/cache
go get gopkg.in/yaml.v2
go get k8s.io/apimachinery/pkg/util/intstr
go get github.com/gambol99/go-marathon
go get github.com/mesosphere/mesos-dns/records/state
go get github.com/mesos/mesos-go/detector
go get github.com/mesosphere/mesos-dns/records
go get github.com/mesos/mesos-go/detector/zoo
go get github.com/mesosphere/mesos-dns/detect
go get github.com/mesosphere/mesos-dns/logging
go get github.com/mesosphere/mesos-dns/util
go get github.com/Masterminds/sprig
go get github.com/rancher/go-rancher/v2
go get github.com/rancher/go-rancher-metadata/metadata
go get github.com/armon/go-proxyproto
go get github.com/vulcand/oxy/buffer
go get github.com/vulcand/oxy/connlimit
go get github.com/vulcand/oxy/ratelimit
go get github.com/ryanuber/go-glob
go get github.com/google/go-github/github
go get github.com/hashicorp/go-version
go get github.com/unrolled/render
go get github.com/pkg/errors

go get github.com/mesos/mesos-go/detector
go get gopkg.in/fsnotify.v1
go get mvdan.cc/xurls
